### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by LeoVerto** [bookbrainz/bookbrainz-site#19]
Currently trying to view a page like http://bookbrainz.org/editor/10 while not being logged in shows an error message (and in debug mode a stacktrace).

**Comment by LordSputnik** [comment]
Errors should always be displayed to the user, with a helpful error message explaining what went wrong, so we can debug it.

We should also change anonymous functions whenever we come across them so that the stack traces for promises and callbacks become more useful

**Comment by leftmostcat** [comment]
Work on this is at least partly done. Entity and user 404s now provide better error messages, and I've improved feedback on login errors as well. I'll leave this open until the next meeting and then close it if nothing else comes up by then.

**Comment by LordSputnik** [comment]
Closing as this is a bit vague - this should be a general goal any time we're adding features.
