### ISSUE TITLE
inboxCount is only refreshed after logging in again

### ISSUE THREAD

**Issue by LeoVerto** [bookbrainz/bookbrainz-site#25]

**Comment by LeoVerto** [comment]
Only tested by sending a message to myself, https://github.com/BookBrainz/python-ws/blob/master/bbws/user.py#L145 might have filtered that though.

**Comment by LordSputnik** [comment]
Try logging out and logging in again.

I couldn't think of a good way to update the inbox count while the user is browsing the site, so at the moment it only refreshes when you log in. I've just thought, we could do it every time the user visits a page, using express's "use" to add in a function that pulls the data.
