### ISSUE TITLE
Make necessary modifications for using behind HTTPS

### ISSUE THREAD

**Issue by LordSputnik** [bookbrainz/bookbrainz-site#38]
Update the site code in whatever way necessary to ensure that once the user is authenticated, they browse the site through HTTPS.

**Comment by leftmostcat** [comment]
Since we've acquired a certificate that shouldn't cause any warnings, we've elected to ditch HTTPS post-login and simply use HSTS so the whole site is TLS-secured. We'll still need some code changes to accommodate this, however.

**Comment by leftmostcat** [comment]
Partially completed by 730c4ccccbcb837dcfbfa33217b0c8000df60a3a and e439623d38024927f05cb9c8abacad8db7b2e919. Depends on bookbrainz/bookbrainz-ws#18 to ensure that we can treat the WS as behind HTTPS if necessary.

**Comment by LeoVerto** [comment]
Seeing as the site works fine behind HTTPS now, this can be closed, can't it?

**Comment by LordSputnik** [comment]
Yup, I think so!
