### ISSUE TITLE
Hide infrequent languages

### ISSUE THREAD

**Issue by LordSputnik** [bookbrainz/bookbrainz-site#41]
No-one is going to write a book in "Enya". Is that a thing? (no offence to users of the Enya language...)

We should constrain our list of languages in the same way MB does.

**Comment by LeoVerto** [comment]
https://en.wikipedia.org/wiki/Enya

**Comment by LordSputnik** [comment]
Yeah, I'm fairly sure it doesn't mean her!

**Comment by leftmostcat** [comment]
Implemented in 05c7145b5e3a33d3af81c0c7c2a7debf3371adad and bookbrainz/bookbrainz-ws@f9bb2c398f67f75112c9d2ff8c67b79b5e5a0193. As per MusicBrainz, a frequency value of 0 for the language hides it, and higher frequency values are sorted first in the languages list.
