### ISSUE TITLE
Add basic search functionality

### ISSUE THREAD

**Issue by leftmostcat** [bookbrainz/bookbrainz-site#44]
A basic search function is needed to enable discovery of entities and to make the data useful. A simple elasticsearch-based search should be targeted for the soft launch.

**Comment by leftmostcat** [comment]
The web service now exposes a /search endpoint which takes a parameter "q" over GET. q matches against the default_alias.name property of all entities. /search/reindex can be called to regenerate the index against all entities if there's a failure somewhere.

**Comment by LordSputnik** [comment]
Closed as of b26076fdd115d8499e811475d65a0f4afeaa3e77
