### ISSUE TITLE
Avoid importing the configuration into helpers/bbws

### ISSUE THREAD

**Issue by LordSputnik** [bookbrainz/bookbrainz-site#46]
This module, and the data models that use it, would be very valuable in the current client JS. However, we can't use them unless the whole configuration is no longer passed in - there is private information there which shouldn't be sent to browsers.

Whether we need this will depend on how we modify the client/server interaction after 0.15.3.

**Comment by leftmostcat** [comment]
We could accomplish this by creating an init function which takes an options arg. Agreed that we should discuss this after knowing what the client-side will look like, though.

**Comment by LordSputnik** [comment]
Invalid now that we're aiming to minimize WS access in the client JS, and we can pass the WS URL in as a prop where needed.
