### ISSUE TITLE
Add title attributes to icon-only buttons

### ISSUE THREAD

**Issue by LeoVerto** [bookbrainz/bookbrainz-site#52]
CatQuest pointed out that understanding what an icon does can be difficult for some people.

We already provide a way for screenreaders to get a text description but hovering over a button should provide it for everyone.

**Comment by LordSputnik** [comment]
I think CatCat wanted test on the buttons by default, as well as the icon:

http://chatlogs.musicbrainz.org/bookbrainz-devel/2015/2015-04/2015-04-07.html#T16-46-08-519493

I don't have anything against that, but only if the buttons don't become too large.

**Comment by LeoVerto** [comment]
Oh yeah, misread that.

I'll look into adding texts to the buttons.

**Comment by LordSputnik** [comment]
http://tickets.musicbrainz.org/browse/BB-52

**Comment by LordSputnik** [comment]
Closing - moved to JIRA.
