### ISSUE TITLE
Internal Server Error for Incorrect User Data

### ISSUE THREAD

**Issue by sils1297** [bookbrainz/bookbrainz-site#70]
Hi, I'm getting an internal server error when trying to log in after registering a fresh account.

**Comment by LordSputnik** [comment]
On bookbrainz.org? I've just tested registration and login on bookbrainz.mbsandbox.org (running the same code), but it doesn't seem to encounter any issues.

**Comment by anniezhou301** [comment]
An internal server error does pops up with a wrong input or no input at all.

**Comment by sils1297** [comment]
Ah indeed, I relied on the auto fill in to fill the form which filled my email address. So yeah wrong input -> 500

**Comment by LordSputnik** [comment]
Ported to JIRA at http://tickets.musicbrainz.org/browse/BB-150
