### ISSUE TITLE
JIRA or GitHub

### ISSUE THREAD

**Issue by sils1297** [bookbrainz/bookbrainz-site#71]
Apparently you seem to use JIRA and GitHub for issue tracking, making it a bit confusing for users - where should stuff be reported? If its JIRA, maybe deactivate GitHub issue tracking, if GitHub, the other way round?

**Comment by LordSputnik** [comment]
Oh, I didn't even know you could disable issue tracking in GitHub. I'll go over the existing issues and close or move to JIRA. Thanks for the heads up.
